import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";

// css
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer position="top-left" />
        {children}
      </body>
    </html>
  );
}
